ARG osrepo=aursu/centos
ARG os=7.9.2009

FROM ${osrepo}:${os}-scm

ARG codename=el
ARG osmajor=7
ARG platform=puppet8

ENV PATH=/opt/puppetlabs/puppet/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

WORKDIR /root

RUN yum -y install \
        diffutils \
        tar \
        vim \
    && yum clean all && rm -rf /var/cache/yum /var/lib/rpm/__db*

RUN rpm -Uvh https://yum.puppet.com/${platform}-release-${codename}-${osmajor}.noarch.rpm \
    && yum -y install puppet-bolt \
       openssh-server \
    && yum clean all && rm -rf /var/cache/yum /var/lib/rpm/__db*

COPY tests/redhat/sshd/sshd_config /etc/ssh/sshd_config
COPY --chmod=600 tests/redhat/sshd/ssh_host_ed25519_key /etc/ssh/ssh_host_ed25519_key
COPY --chmod=640 tests/redhat/sshd/known_hosts /root/.ssh/known_hosts

RUN ssh-keygen -f /root/.ssh/id_rsa -N '' <<<y \
    && cp -a .ssh/id_rsa.pub .ssh/authorized_keys

RUN cp /etc/skel/.bash_profile /etc/skel/.bashrc ~/ \
    && echo 'export PATH=/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin:$PATH' >> ~/.bashrc

RUN mkdir -p /var/tmp && chmod 1777 /var/tmp

COPY . /root/puppet/lsys_postgresql
WORKDIR /root/puppet/lsys_postgresql/tests/bolt

CMD ["/usr/sbin/sshd", "-D"]