# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.1.2"
      puppet_version: ">= 6.0.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    cron_core:
      repo: "puppetlabs/cron_core"
      ref: "1.0.5"
      puppet_version: ">= 6.0.0"
    host_core:
      repo: "puppetlabs/host_core"
      ref: "1.0.3"
      puppet_version: ">= 6.0.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "6.6.0"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref: "4.0.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref: "7.10.0"
    r10k:
      repo: "puppet/r10k"
      ref: "8.3.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.3.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.7"
      puppet_version: ">= 6.0.0"
  repositories:
    lsys:
      repo: https://github.com/aursu/puppet-lsys.git