# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 10.0.1
    augeas_core:
      repo: puppetlabs/augeas_core
      puppet_version: ">= 6.0.0"
    concat:
      repo: puppetlabs/concat
      ref: 9.0.0
    cron_core:
      repo: puppetlabs/cron_core
      puppet_version: ">= 6.0.0"
    firewall:
      repo: puppetlabs/firewall
      ref: 8.1.3
    host_core:
      repo: puppetlabs/host_core
      puppet_version: ">= 6.0.0"
    inifile:
      repo: puppetlabs/inifile
      ref: 6.1.0
    lsys_postgresql:
      repo: aursu/lsys_postgresql
      ref: 0.52.1
    openssh:
      repo: aursu/openssh
      ref: 0.9.6
    postgresql:
      repo: puppetlabs/postgresql
      ref: 10.3.0
    puppet_agent:
      repo: puppetlabs/puppet_agent
      ref: 4.22.0
    puppetdb:
      repo: puppetlabs/puppetdb
      ref: 8.1.0
    r10k:
      repo: puppet/r10k
      ref: 14.3.0
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.7.0
    systemd:
      repo: puppet/systemd
      ref: 6.0.0
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
    bsys:
      repo: aursu/bsys
      ref: 0.10.3
