# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 9.1.0
    augeas_core:
      repo: puppetlabs/augeas_core
      puppet_version: ">= 6.0.0"
    concat:
      repo: puppetlabs/concat
      ref: 9.0.0
    cron_core:
      repo: puppetlabs/cron_core
      puppet_version: ">= 6.0.0"
    host_core:
      repo: puppetlabs/host_core
      puppet_version: ">= 6.0.0"
    inifile:
      repo: puppetlabs/inifile
      ref: 6.1.0
    lsys_postgresql:
      repo: aursu/lsys_postgresql
      ref: 0.47.0
    openssh:
      repo: aursu/openssh
      ref: 0.9.1
    postgresql:
      repo: puppetlabs/postgresql
      ref: 9.1.0
    puppet_agent:
      repo: puppetlabs/puppet_agent
      ref: 4.15.0
    puppetdb:
      repo: puppetlabs/puppetdb
      ref: 7.13.0
    r10k:
      repo: puppet/r10k
      ref: 12.1.1
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.3.0
    systemd:
      repo: puppet/systemd
      ref: 6.0.0
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      puppet_version: ">= 6.0.0"
    bsys:
      repo: aursu/bsys
      ref: 0.6.2
