# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "6.6.0"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref: "4.0.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref: "7.5.0"
    r10k:
      repo: "puppet/r10k"
      ref: "8.3.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.3.0"
  repositories:
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      ref: "tags/1.0.5"
      puppet_version: ">= 6.0.0"
    cron_core:
      repo: https://github.com/puppetlabs/puppetlabs-cron_core.git
      ref: "tags/1.0.4"
      puppet_version: ">= 6.0.0"
    host_core:
      repo: https://github.com/puppetlabs/puppetlabs-host_core.git
      ref: "tags/1.0.3"
      puppet_version: ">= 6.0.0"