version: "3"
services:
  rocky8puppet8bolt:
    build:
      context: .
      dockerfile: tests/redhat/Dockerfile
      args:
        osrepo: aursu/rockylinux
        os: $RL8
        osmajor: 8
    privileged: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    user: root
    image: "aursu/rockylinux:${RL8TAG}-puppet8-bolt"
  stream9puppet8bolt:
    build:
      context: .
      dockerfile: tests/redhat/Dockerfile
      args:
        os: $OS9
        platform: puppet8
    privileged: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    user: root
    image: "aursu/centos:${OS9TAG}-puppet8-bolt"
  ubuntu20puppet8bolt:
    build:
      context: .
      dockerfile: tests/ubuntu/Dockerfile
      args:
        os: $U20
        codename: $U20CODE
    privileged: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    user: root
    image: "aursu/ubuntu:${U20TAG}-puppet8-bolt"
  ubuntu22puppet8bolt:
    build:
      context: .
      dockerfile: tests/ubuntu/Dockerfile
      args:
        os: $U22
        codename: $U22CODE
    privileged: true
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    user: root
    image: "aursu/ubuntu:${U22TAG}-puppet8-bolt"